export enum VisualizerType {
  CUBE = "cube",
  CUBE_NET = "cube-net",
  CUBE_TOP = "cube-top",
  MEGAMINX = "megaminx",
  MEGAMINX_NET = "megaminx-net",
  MEGAMINX_TOP = "megaminx-top",
  PYRAMINX = "pyraminx",
  PYRAMINX_NET = "pyraminx-net",
  SKEWB = "skewb",
  SKEWB_NET = "skewb-net",
  SQUARE1 = "square1",
  SQUARE1_NET = "square1-net",
  CLOCK = "clock",
}
